CREATE TABLE users (
number SERIAL PRIMARY KEY,
id TEXT UNIQUE NOT NULL,
password TEXT NOT NULL,
name TEXT UNIQUE NOT NULL
);

CREATE TABLE rooms (
number SERIAL PRIMARY KEY,
id TEXT UNIQUE NOT NULL,
password TEXT NOT NULL
);

CREATE TABLE comments (
number SERIAL PRIMARY KEY,
comment TEXT NOT NULL,
date DATE NOT NULL,
user_id INTEGER NOT NULL,
room_number INTEGER NOT NULL
);

CREATE TABLE menbers_info (
number SERIAL PRIMARY KEY,
user_number INTEGER NOT NULL,
room_number INTEGER NOT NULL
);
